### ISSUE TITLE
Inference on an image

### ISSUE THREAD

**Issue by rose-jinyang** [yeliudev/CATNet#12]
Hello
How are you?
Thanks for contributing to this project.
I am going to do inference on an image.
Let me share my script code.

from mmdet.apis import init_detector, inference_detector

config_file = 'configs/isaid/cat_mask_rcnn_r50_aug_1x_isaid.py'
checkpoint_file = 'ckpts/cat_mask_rcnn_r50_aug_1x_isaid-e1fb2a8a.pth'

model = init_detector(config_file, checkpoint_file, device='cpu')

img = 'test_data/googleEarth.JPG'

result = inference_detector(model, img)

When I ran the above code on Windows, I got the following issue.

![image](https://github.com/yeliudev/CATNet/assets/47862419/73dab241-42a7-46a1-8c73-d3e717605b25)

**Comment by yeliudev** [comment]
Please refer to the inference code of `mmdet==2.17.0`.
