### ISSUE TITLE
Great job, can you please provide the script of cut iSAID dataset, or share your idea about how do you deal with for cut image patch，thanks you!

### ISSUE THREAD

**Issue by wuyunxiangwyx** [yeliudev/CATNet#3]

**Comment by yeliudev** [comment]
Hi @wuyunxiangwyx! Thanks for your interest in our work.

I'm afraid that the original script for cropping images is missing, but here are some bullet points on how to obtain the patches:

1. For all the patches, both sides are no more than 512px. Neighboring patches have 128px overlaps.
2. If the total width or length of an image is smaller than 512px, the final patches are smaller than 512px as well.
3. For each side, if the final patch goes out of the original image, this patch will be shifted back to fit the actual size, thus the overlap between this patch and the last patch is larger than 128px.

For example, if the original image is `1000 (width) x 300 (height)`, and the origin point is at the top-left, the cropped patches are `0-0-512-300`, `384-0-896-300`, and `488-0-1000-300` (in ltx-lty-rbx-rby style).
