### ISSUE TITLE
我目前遇到的报错是这样的（chatGPT回答我的），请问我该怎么解决呢？麻烦您解答我以下，谢谢

### ISSUE THREAD

**Issue by gsj-zk** [yeliudev/CATNet#9]
这段代码的错误提示中有两部分。第一部分是 PyTorch 分布式处理模块的警告信息，它告诉你为了避免过度加载系统，为每个进程设置了环境变量 OMP_NUM_THREADS 为 1。第二部分是一些导入错误，其中 mmcv.ops 中的一个模块 assign_score_withk.py 在导入过程中出错，该模块依赖于扩展模块，而该扩展模块可能由于没有正确安装或编译而导致错误。你可以检查是否正确安装了 mmcv，或者尝试重新编译该模块。
我的mmcv-full确实是安装上了的，且版本是1.3.18，但是我不知道到底缺少了哪个扩展模块

**Comment by yeliudev** [comment]
It seems that mmcv was not compiled successfully, please check the mmcv installation.
